
services:
  backend:
    build: .
    image: guilhermebrida/short-my-url:latest
    container_name: short-my-url
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: default_secret_key
      DATABASE_URL: postgresql://smu_owner...
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
